In [19]:
def is_number_valid(row,col,num):
    global grid
    for i in range(0,9):
        if grid[row][i]==num:
            return False
    for i in range (0,9):
        if grid[i][col]==num:
            return False
    col_subset = (col//3) * 3
    row_subset = (row//3) * 3
    for i in range(0,3):
        for j in range (0,3):
            if grid[row_subset+i][col_subset+i]==num:
                return False
    return True
        
        

In [20]:
def solve_sudoku():
    global grid
    for row in range (0,9):
        for col in range (0,9):
            if grid[row][col]==0:
                for num in range (1,10):
                    if is_number_valid(row,col,num):
                        grid[row][col] = num
                        solve_sudoku()
                        grid[row][col]=0
                return
    print(np.matrix(grid))
                        
                    
                

In [23]:
grid = [[3,0,4,0,0,5,7,0,0],
        [7,0,0,2,0,9,0,6,4],
        [6,2,0,7,3,4,0,5,8],
        [1,0,9,0,6,0,2,4,7],
        [8,0,2,0,4,6,1,0,5],
        [0,4,0,1,0,2,0,7,3],
        [2,6,0,0,0,1,0,3,0],
        [4,5,0,0,2,0,0,8,0],
        [0,0,0,4,0,3,0,0,0]
       ]

solve_sudoku()

[[3 9 4 6 8 5 7 1 2]
 [7 8 5 2 1 9 3 6 4]
 [6 2 1 7 3 4 9 5 8]
 [1 3 9 5 6 8 2 4 7]
 [8 7 2 3 4 6 1 9 5]
 [5 4 6 1 9 2 8 7 3]
 [2 6 7 8 5 1 4 3 9]
 [4 5 3 9 2 7 6 8 1]
 [9 1 8 4 7 3 5 2 6]]
